plugins { id 'com.android.application' }
android {
 namespace 'io.mo.glassmic.xposed'
 compileSdk 35
 ndkVersion '26.1.10909125'
 defaultConfig {
  applicationId 'io.mo.glassmic.embeddedtest'
  minSdk 29
  targetSdk 35
  versionCode 1
  versionName '0.1'
  ndk { abiFilters 'arm64-v8a' }
  externalNativeBuild { cmake { arguments '-DANDROID_STL=c++_static'; cppFlags '-std=c++17', '-fvisibility=hidden', '-fno-exceptions', '-fno-rtti' } }
 }
 buildFeatures { prefab true }
 externalNativeBuild { cmake { path 'src/main/cpp/CMakeLists.txt'; version '3.22.1' } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
 buildTypes { debug { minifyEnabled false } }
}
dependencies { implementation 'com.bytedance.android:shadowhook:1.0.10' }
